#!/usr/bin/env python
#coding: utf-8
#
#Copyright (c) 2010 Kilian Valkhof, Paul Chaplin, Tarnay Kálmán
#
#Permission is hereby granted, free of charge, to any person
#obtaining a copy of this software and associated documentation
#files (the "Software"), to deal in the Software without
#restriction, including without limitation the rights to use,
#copy, modify, merge, publish, distribute, sublicense, and/or sell
#copies of the Software, and to permit persons to whom the
#Software is furnished to do so, subject to the following
#conditions:
#
#The above copyright notice and this permission notice shall be
#included in all copies or substantial portions of the Software.

import os, sys
import subprocess
import trimage

if __name__ == "__main__":
    path = os.path.join(os.path.dirname(fluxgui.__file__), "fluxgui.py")
    subprocess.call([sys.executable, path] + sys.argv[1:])

